# Introduction Numpy

In [7]:
# operasi penjumlahan vektor
# menggunakan list

a = [1, 2, 3, 3]
b = [5, 1, 2, 6]

def jumlah (a,b):
    c = [0] * len(a)
    for i in range(len(a)):
        c[i] = a[i] + b[i]
    return c

In [8]:
jumlah(a,b)

[6, 3, 5, 9]

In [9]:
# tipe data dari numpy -> np.array

import numpy as np
a = [1, 2, 3, 4]
b = [6, 4, 2, 7]

np_a = np.array(a)
np_b = np.array(b)

In [12]:
a + b

[1, 2, 3, 4, 6, 4, 2, 7]

In [13]:
np_a + np_b 

array([ 7,  6,  5, 11])

In [16]:
# cek performa

a = [1,2,3,4,5,6,7,8,9,10]
b = [1,1,1,1,1,1,1,1,1,1,]

In [17]:
%timeit jumlah(a,b)

7.16 µs ± 1.37 µs per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [18]:
np_a = np.array(a)
np_b = np.array(b)

%timeit np_a + np_b

2.93 µs ± 397 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
# contoh array

a1d = [1,2,3,4,5]
a1d = np.array(a1d)
a1d

array([1, 2, 3, 4, 5])

In [20]:
a2d = [[1,3], [5,4], [7,8]]
a2d = np.array(a2d)
a2d

array([[1, 3],
       [5, 4],
       [7, 8]])

In [21]:
a2d = [[1,3], [5,4,5], [7,8]]
a2d = np.array(a2d)
a2d

C:\Users\ASUS\AppData\Local\Temp\ipykernel_2044\3167342458.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2d = np.array(a2d)


array([list([1, 3]), list([5, 4, 5]), list([7, 8])], dtype=object)

In [22]:
a = [1,2,3,4,5.4]
a = np.array(a)
a


array([1. , 2. , 3. , 4. , 5.4])

In [23]:
A = [[1,3], [5,4], [7,8]]
A = np.array(A)
A

array([[1, 3],
       [5, 4],
       [7, 8]])

In [33]:
# cara memanggil elemen dalam matriks
# baris dulu baru kolom [b][k]

A[2][1]

8

In [27]:
# memanggil baris

A[1]

array([5, 4])

In [31]:
# memanggil kolom

A[1, :]

array([5, 4])

In [32]:
A[: , 0]

array([1, 5, 7])

## Special Array

In [34]:
# special array

np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
# didalam memori diberi angka nol

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [38]:
# didalam memori tidak ada angka, nilainya tergantung pada inisiasi/syntax sebelumnya

np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.arange(1, 6, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [40]:
# (angka awal, angka akhir, jml angka)

np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [41]:
A = [[1,3], [5,4], [7,8]]
A = np.array(A)
A

array([[1, 3],
       [5, 4],
       [7, 8]])

In [42]:
A.size

6

In [43]:
A.ndim

2

In [44]:
A.shape

(3, 2)

In [45]:
a = [2,3,1,6,5,7,5,6]
a = np.array(a)
a

array([2, 3, 1, 6, 5, 7, 5, 6])

In [50]:
a[np.newaxis]

array([[2, 3, 1, 6, 5, 7, 5, 6]])

In [51]:
a[:, np.newaxis]

array([[2],
       [3],
       [1],
       [6],
       [5],
       [7],
       [5],
       [6]])

In [46]:
a.reshape((2,4))

array([[2, 3, 1, 6],
       [5, 7, 5, 6]])

In [47]:
a.reshape((4,2))

array([[2, 3],
       [1, 6],
       [5, 7],
       [5, 6]])

In [48]:
# transpose matriks

a.reshape((4,2)).T

array([[2, 1, 5, 5],
       [3, 6, 7, 6]])

In [52]:
np.expand_dims(a, axis=1).shape

(8, 1)

## Querying

In [53]:
mat = [[5,4,3,8,2], [4,6,3,7,4], [1,6,4,5,6]]
mat = np.array(mat)
mat 

array([[5, 4, 3, 8, 2],
       [4, 6, 3, 7, 4],
       [1, 6, 4, 5, 6]])

In [59]:
mat[1:2, -2:]

array([[7, 4]])

In [61]:
mat[:, 2]

array([3, 3, 4])

In [62]:
mat > 4

array([[ True, False, False,  True, False],
       [False,  True, False,  True, False],
       [False,  True, False,  True,  True]])

In [63]:
mat[mat > 4]

array([5, 8, 6, 7, 6, 5, 6])

In [66]:
mahasiswa = np.array(['Afif', 'Fahmi', 'Danu', 'Raka'])
nilai = np.array([98.7, 75.3, 53.4, 45.2])

In [68]:
nilai[nilai > 60]

array([98.7, 75.3])

In [69]:
kondisi = nilai < 60
mahasiswa[kondisi]

array(['Danu', 'Raka'], dtype='<U5')

In [72]:
A = np.array([[1,2], [3,4]])
B = np.array([[6,5], [2,7]])
C = np.array([1,2])

In [74]:
A+B

array([[ 7,  7],
       [ 5, 11]])

In [75]:
A*B

array([[ 6, 10],
       [ 6, 28]])

In [76]:
# perkalian matriks secara aljabar linear

A@B

array([[10, 19],
       [26, 43]])

In [79]:
A

array([[1, 2],
       [3, 4]])

In [80]:
A.sum(axis = 1)

array([3, 7])

In [81]:
A.mean(axis = 0)

array([2., 3.])

In [84]:
np.random.random([2,3])

array([[0.72819593, 0.85077908, 0.0608153 ],
       [0.24288462, 0.54556076, 0.74547223]])