## List

In [1]:
my_list = [1 ,2 , 3]
my_list

[1, 2, 3]

In [2]:
my_list + [4, 5]

[1, 2, 3, 4, 5]

In [3]:
my_list * 2

[1, 2, 3, 1, 2, 3]

In [6]:
my_list.append(4)
my_list

[1, 2, 3, 4, 4]

In [7]:
my_list.append([5,6])
my_list

[1, 2, 3, 4, 4, [5, 6]]

In [11]:
mylist = [1, 2, 3]

In [12]:
mylist.extend([4, 5, 6])
mylist

[1, 2, 3, 4, 5, 6]

In [15]:
mylist.remove(4)
mylist

[1, 2, 3, 5]

In [17]:
my_list.remove([5, 6])
my_list

[1, 2, 3, 4, 4]

## Dictionaries

In [19]:
student = {'name' : 'Raka', 'age' : 18}

In [20]:
employee = {'cto' :{'name' : 'Raka', 'age' : 18}}

In [32]:
student = dict(name='Billy', age=38)

In [24]:
student['name']

Billy


In [33]:
del student['age']

In [34]:
student

{'name': 'Billy'}

In [35]:
student = {'name' : 'Raka', 'age' : 17}

In [36]:
student.keys()

dict_keys(['name', 'age'])

In [38]:
student.values()

dict_values(['Raka', 17])

## Tuples

In [39]:
people = ('Raka', ('Kode', 'Random'))

In [40]:
people

('Raka', ('Kode', 'Random'))

In [41]:
people[0]

'Raka'

In [42]:
people[1]

('Kode', 'Random')

In [43]:
people[1][0]

'Kode'

In [44]:
number = (1,2,3,4)

In [46]:
new_number = number[0], number[1:3]
new_number

(1, (2, 3))

In [47]:
email_attr = ('to', 'from', 'cc', 'bcc', 'subject', 'body')

In [48]:
# mengubah tuples menjadi list

email_attr_list = list(email_attr)

In [49]:
# mengurutkan list dengan "sort"

email_attr_list.sort()
email_attr_list

['bcc', 'body', 'cc', 'from', 'subject', 'to']

## Files

In [52]:
# membuka file

myfile = open('text.txt', 'w')

In [53]:
# menulis file

myfile.write('halo text file!\n')
myfile.write('selamat tinggal text file!\n')

27

In [54]:
# menutup dan menyimpan file

myfile.close()

In [55]:
myfile = open('text.txt')

In [56]:
myfile.readline()

'halo text file!\n'

In [57]:
myfile.readline()

'selamat tinggal text file!\n'

In [59]:
open('text.txt').read()

'halo text file!\nselamat tinggal text file!\n'

In [60]:
print(open('text.txt').read())

halo text file!
selamat tinggal text file!



In [61]:
x, y, z = 43, 44, 45

In [62]:
message = 'Spam'

In [63]:
data = {'a' : 1, 'b' : 2 }

In [64]:
list = [1,2,3]

In [68]:
file = open('text.txt', 'w')
file.write(message + '\n')
file.write('%s,%s,%s\n' % (x,y,z))

9

In [69]:
file.write(str(list) + '$' + str(data) + '\n')

27

In [70]:
file.close()

## While Loops

In [1]:
message = "spam"
while message != '':
    print(message, end=' ')
    message = message[1:]

spam pam am m 

In [2]:
a = 0
b = 13
while a<b:
    print(a, end=' ')
    a = a + 1

0 1 2 3 4 5 6 7 8 9 10 11 12 

In [1]:
while True:
    name = input('Enter name : ')
    if name == 'stop':break
    age = input('Enter age : ')
    print('Hello', name, '=>', int(age) ** 2)

## For Loops

In [1]:
for word in ['raka', 'billy', 'kode']:
    print(word, end='\n')

raka
billy
kode


In [2]:
sum = 0
for i in [1,2,3,4]:
    sum = sum + i

sum

10

In [3]:
prod = 1
for item in [1,2,3,4]:
    prod *= item

prod

24

In [5]:
text = 'foxy fox'
words = ('is', 'great', 'animal')
for chara in text:
    print(chara, end=' ')

f o x y   f o x 

In [6]:
for word in words:
    print(word, end='...')

is...great...animal...

In [7]:
coor = [(1,2), (3,4), (5,6)]
for(x,y) in coor:
    print(x,y)

1 2
3 4
5 6


## IF Statement

In [8]:
if 1:
    print('true')
if not 1:
    print('true')
else:
    print('false')

true
false


In [9]:
age = input('enter your age :')
if int(age) * 365 > 20000:
    print('time to retire!')
elif int(age) * 365 > 10000:
    print('lots of time left!')
else:
    print('time to get started!')

In [1]:
user_age = input('enter your age :')
age = int(user_age) * 365

if age >= 9490:
    print('you are a Jedi Master now. Go learn from Master Yoda!')
elif age >= 8395 and age < 9490:
    print('becoming Jedi Knight')
else:
    print('you are a young Padawan')

In [1]:
x = 10
y = 50
if (x ** 2 > 100 and y < 100):
    print(x,y)

## Functions

In [2]:
def add (a,b):
    return a + b

In [3]:
add(5,4)

9

In [4]:
add_things = add(10,4)
add_things

14

In [5]:
def add_and_print (a,b):
    print(a + b)

In [6]:
add_and_print(1,3)

4


In [7]:
x = add_and_print(5,3)

8


In [9]:
def intersection (first_word, second_word):
    result = []
    for x in first_word:
        if x in second_word:
            result.append(x)
    return result

In [10]:
word1 = 'spam'
word2 = 'scam'
char_of_intersect = intersection(word1, word2)
char_of_intersect

['s', 'a', 'm']

## Modules and Buid-in Function

In [1]:
abs(-123)

123

In [3]:
numbers = [1,2,3]
isinstance(numbers, list)

True

In [4]:
isinstance(numbers, dict)

False

In [5]:
numbers = [1,2,3,4,5,6]
max(numbers)

6

In [6]:
min(numbers)

1

In [8]:
alphas = ['a','b','z']
print(max(alphas))
print(min(alphas))

z
a


In [9]:
language = ['py','js','go','c']
language.index('go')

2

In [11]:
language.sort()
language

['c', 'go', 'js', 'py']

In [12]:
name = 'raka'
name.replace('k','c')

'raca'

In [13]:
name.capitalize()

'Raka'

In [16]:
import math
math.factorial(3)

6

In [17]:
from math import factorial
from datetime import datetime
print(factorial(3))
print(datetime.now())

6
2022-09-05 11:29:50.961444


## Numpy

In [23]:
import numpy as np

In [24]:
height = [1.75, 1.68, 1.8, 1.81, 1.69]
weight = [66.4, 49.22, 66.3, 88.56, 65.4]

In [27]:
np_height = np.array(height)
np_weight = np.array(weight)

In [28]:
bmi = np_weight / np_height ** 2
bmi

array([21.68163265, 17.43905896, 20.46296296, 27.03214188, 22.8983579 ])

In [32]:
bmi[bmi > 24]

array([27.03214188])

In [29]:
mix_array = np.array([1.0, 'is', True])
mix_array

array(['1.0', 'is', 'True'], dtype='<U32')

In [30]:
numlist = [1,2,3]
np_array = np.array([1,2,3])
numlist + numlist

[1, 2, 3, 1, 2, 3]

#### ~ Numpy Array 2D

In [34]:
import numpy as np

In [43]:
height = np.array([1.75, 1.68, 1.8])
weight = np.array([66.4, 49.22, 66.3])

In [44]:
type(height)

numpy.ndarray

In [45]:
np_2d = np.array([[1.75, 1.68, 1.8], 
                [66.4, 49.22, 66.3]])

In [46]:
# shape = (baris,kolom)

np_2d.shape

(2, 3)

In [47]:
np_2d[0]

array([1.75, 1.68, 1.8 ])

In [48]:
np_2d[0][2]

1.8

In [49]:
np_2d[:, 1:3]

array([[ 1.68,  1.8 ],
       [49.22, 66.3 ]])

In [50]:
np_2d[1, :]

array([66.4 , 49.22, 66.3 ])

#### ~ Statistik Dasar dengan Numpy

In [51]:
import numpy as np

In [52]:
height = np.round(np.random.normal(1.75, 0.2, 5000), 2)
height

array([1.58, 1.8 , 1.68, ..., 1.64, 1.71, 1.81])

In [53]:
len(height)

5000

In [54]:
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
weight

array([85.16, 26.56, 58.03, ..., 52.85, 63.51, 50.52])

In [55]:
len(weight)

5000

In [56]:
np_city = np.column_stack((height, weight))

In [57]:
np.mean(np_city[:,0])

1.749912

In [58]:
np.median(np_city[:,0])

1.75

In [59]:
np.std(np_city[:,0])

0.19995087460673933